### ISSUE TITLE
Unable to retrieve data for test user

### ISSUE THREAD

**Issue by michaelcarter** [hmrc/individuals-paye#96]
I'm trying to integrate the individuals PAYE API with my ruby app, and am having trouble with test users. 

I can complete the OAuth process with a test user without problems, and create test data for them too. However, when I then query the API for data from a particular tax year, no data is returned.

The code below is taken from my application at the point it receives an authorisation code after the test user authorises my app. The last request, returns a `{"code"=>"NOT_FOUND", "message"=>"The requested resource could not be found."}` JSON response. I seem to get this response no matter which tax year I query for.

```ruby
# This is working:
request = HTTParty.post(
  "https://test-api.service.hmrc.gov.uk/oauth/token",
  body: {
    client_id: "my-client-id",
    client_secret: "my-client-secret",
    redirect_uri: "my-redirect-uri",
    grant_type: "authorization_code",
    code: params["code"]
  }.to_json,
  headers: {
    "Content-Type" => "application/json",
    "Accept" => "application/json"
  }
)

token = request.parsed_response["access_token"]

# This also seems to work:
HTTParty.post(
  "https://test-api.service.hmrc.gov.uk/individual-paye-test-support/paye/nino/RM342470A/tax-year/2016-17",
  body: {"scenario": "EVERYTHING"}.to_json,
  headers: {
    "Content-Type" => "application/json",
    "Accept" => "application/vnd.hmrc.2.0+json",
    "Authorization" => "Bearer #{token}"
  }
)

# This is returning the error:
HTTParty.get(
  "https://test-api.service.hmrc.gov.uk/individuals/paye/nino/RM342470A/tax-year/2016-17",
  headers: {
    "Content-Type" => "application/json",
    "Accept" => "application/vnd.hmrc.1.1+json",
    "Authorization" => "Bearer #{token}"
  }
)
```

Any help anyone could offer would be much appreciated. Apologies in advance if I've missed something blindingly obvious in your documentation.

**Comment by emrawsy** [comment]
This issue is being dealt with through channel from Developer Hub. Support issues can be raised through [this link](https://developer.service.hmrc.gov.uk/developer/support)
